### ISSUE TITLE
[question] Attaching images

### ISSUE THREAD

**Issue by waygou** [manogi/nova-tiptap#1]
Hi manogi,

The image component upload works on this editor? Do you know how I can use it?

Thanks,
Bruno

**Comment by manogi** [comment]
Hi Bruno,
the image component ist not yet implemented. It is on the roadmap.
Thanks for your patience, Sebastian

**Comment by waygou** [comment]
Sorry my bad, you wrote it there is. Thanks! Great package, congrats!

**Comment by manogi** [comment]
To be honest I added the roadmap to the readme after your question here   😬

**Comment by StanBarrows** [comment]
Heyho, awesome package! 

Can we somehow support you with the image-implementation =)?

Cheers,
Stan

**Comment by manogi** [comment]
Hi Stan,

thank you very much for offering your help.

I can only work week-ends on my open source projects, and having family and a kid that does not leave me much time, BUT: last week-end I started reprogramming the package to use the latest version of the tiptap editor (which includes some major changes), and I hope I will finish that this week-end.

After that, I'd be glad If you looked into implementing the image part, but before it does not make much sense, I think.

Thanks again, Sebastian

**Comment by StanBarrows** [comment]
That sounds like a plan! Happy Weekend =)

**Comment by manogi** [comment]
Hi @StanBarrows, I updated the project. The package is in sync with the current vue-tiptap version, so if you find the time please feel free to tinker with the idea of implementing the image part.
I will also think about it next weekend ;-)

**Comment by niladam** [comment]
Hello. Any news on this ?
