### ISSUE TITLE
Label name not showing on details view

### ISSUE THREAD

**Issue by doriandigital** [manogi/nova-tiptap#10]
When using the TipTap editor, the label name is not showing on the details view.

In cases when you have more than one editor field per view, it can be a bit tricky to figure out which field is which.

![details-view](https://user-images.githubusercontent.com/43826880/69801621-8f66c180-11cf-11ea-8a45-9e47fd1d9719.jpg)

**Comment by manogi** [comment]
You are right, and this is fixed now in 0.3.6. Thanks for pointing this out.
