### ISSUE TITLE
`<h4>, <h5>, <h6>` tags are converted to `<p>`

### ISSUE THREAD

**Issue by TimothePearce** [manogi/nova-tiptap#12]
## Description
The `<h4></h4>`, `<h5></h5>` or `<h6></h6>` tags are converted to a `<p></p>` when while editing the content.

## Example
During creation, my tags are properly formatted: 
![Capture d’écran 2019-12-30 à 19 10 46](https://user-images.githubusercontent.com/11693661/71594440-34125100-2b38-11ea-8a99-871b7ad33a29.png)

Wich is not the case when I'm editing the same content:
![Capture d’écran 2019-12-30 à 19 11 56](https://user-images.githubusercontent.com/11693661/71594478-60c66880-2b38-11ea-94f0-fca7b37b8a4e.png)

**Comment by manogi** [comment]
PR fix merged and new version released, thanks!
