### ISSUE TITLE
Is there support for Embeds?

### ISSUE THREAD

**Issue by Jonpolygon** [manogi/nova-tiptap#17]
I couldn't see in the documentation or code, but is there a way to add embeds, specifically YouTube?

**Comment by manogi** [comment]
This could be added. I will keep this issue open, but I am not sure when I will find the time. PRs are welcome.

**Comment by manogi** [comment]
@Jonpolygon you can now use the "edit_html" button and then paste in iframes (f.e. the youtube embed) in the HTML view.

**Comment by Payetus** [comment]
This is not working. Iframe get sanatized

**Comment by timstats91** [comment]
> This is not working. Iframe get sanatized

This is exactly what I'm trying to do. I want to embed youtube videos and tried via "edit html" but doesn't work. Any chance this could changed/fixed?
