### ISSUE TITLE
Request: add source code edit mode 

### ISSUE THREAD

**Issue by lptn** [manogi/nova-tiptap#19]
froala/nova-froala-field has a very useful (in some cases) mode to edit raw HTML. Is it possible to implement the same for this field/editor?

**Comment by manogi** [comment]
Hi there - this is not planned. As the content ist not stored as HTML but as a JSON object, there is not real raw HTML to edit in the first place.

**Comment by manogi** [comment]
Well - the original tiptap editor - which this is a wrapper for - actually has the possibility to switch from JSON to HTML. I will keep this open so far and see if I can add this.

**Comment by manogi** [comment]
Added in 0.5.0 - thanks to @tmorian.
