### ISSUE TITLE
class Manogi\Tiptap not found

### ISSUE THREAD

**Issue by doriandigital** [manogi/nova-tiptap#2]
When following the documentation and adding Tiptap::make('something'), I am presented with the following exception "class Manogi\Tiptap not found"

I declared the following dependency in the class:

use Manogi\Tiptap;

I also tried "use TipTap" and "Laravel\Nova\Fields\TipTap".

Any idea what could be the issue?

**Comment by manogi** [comment]
The correct use statement is `use Manogi\Tiptap\Tiptap;`
Which editor do you use? Editors like Sublime Text, VS Code, PHPStorm should be able to help you with using the right "use" statements (some of them need plugins for that).

**Comment by manogi** [comment]
But thanks for mentioning this, I will add it to the Documentation and Readme.
