### ISSUE TITLE
Request: Always Show Content

### ISSUE THREAD

**Issue by mstaack** [manogi/nova-tiptap#22]
Add an option to always show the complete content.
Like in TextArea Field:

```
Textarea::make('Intro')->alwaysShow(),
```

**Comment by saleh-mir** [comment]
+1

**Comment by manogi** [comment]
Textarea and Trix work a bit differently, as they are always completely hidden and `alwaysShow()` then completely reveals the content.

As I kind of missed the opportunity to do the same, I am now hesitant to take that method name and give it a different meaning. Shouldn't it actually act exactly the same as with Trix and Textarea?

This is what I plan to do, but is it a "breaking change" or can I just add it in the next minor version?

**Comment by manogi** [comment]
OK - I decided to up the version to 1.0 now. So we now have the exact same behavior as Trix and Textarea: `alwaysShow()` works the same way and the field is hidden from the index view by default.

**Comment by mstaack** [comment]
brilliant, thanks 🚀
