### ISSUE TITLE
Extend with superscript?

### ISSUE THREAD

**Issue by Reached** [manogi/nova-tiptap#25]
Hi there,

Great package!

I wonder if it's possible to add your own extensions? Currently want to add superscript and subscript support, and I found this plugin for tiptap: https://github.com/hanspagel/tiptap-extension-superscript is there any way currently to make it work with this package? :)

Thanks!

**Comment by manogi** [comment]
I added superscript and subscript support. Not sure if and when I will get to build in extendability.

**Comment by Reached** [comment]
@manogi not sure why I didn't see this, but thank you so much!
