### ISSUE TITLE
Font coloring and text alignment

### ISSUE THREAD

**Issue by albalooshi** [manogi/nova-tiptap#3]
Is there any plans to support color coloring? Also text alignment would also be great. 
Thanks

**Comment by manogi** [comment]
Hey there. 

I will put text alignment on the roadmap.

I don't know about coloring: I don't see the editor as a WYSIWYG editor. The content should just represent the structure of the text, not the styling. So coloring will probably not be part of it. 

In an ideal world the content should just as well be representable as Markdown or even an JSON object, so even text alignment bends those rules a bit.

Thank you for your input, Sebastian

**Comment by albalooshi** [comment]
@manogi 
Thank you for your reply, Any updates regarding the text alignment? I would like to use this package in one of my projects :).

**Comment by manogi** [comment]
As I have a lot of client work to do in the moment and this is a project I work on in my free time it will have to wait at least until the weekend.

**Comment by manogi** [comment]
The more I think about it: I don't think I will add text alignment in the foreseeable future. I just don't see text formatting outside of what can be done by Markdown as part of this project.

Also sorry again for not working on the project for quite some time - I just don't have the time at the moment. I will continue at some point in the future though - there is a whole new major version now of the underlying actual tiptap editor project that I have to catch up with.
