### ISSUE TITLE
Add field name to id attribute

### ISSUE THREAD

**Issue by u12206050** [manogi/nova-tiptap#32]
Following convention of all other Nova fields there should exist an id attribute on the element with `tiptap-content` class containing the name of the field.

Let me know if you need help with this.

**Comment by manogi** [comment]
Hi there,
if you'd like to PR this I'd gladly look into it and merge it quickly if the PR looks OK.
Thanks!

**Comment by manogi** [comment]
Hi again,
I have not looked into this very deeply, but the div `tiptap-content` contains another div which then contains the actual HTML which is stored in the database. Are you sure that not the div containing the HTML should get the ID?

**Comment by u12206050** [comment]
I think it is best on the top level which wraps the whole field in. Anyone can then parse it down further if needed. PR coming soon.

**Comment by u12206050** [comment]
#33 Done. Didn't rebuild since I guess you can already have it setup locally.
