### ISSUE TITLE
Add title attributes to toolbar buttons

### ISSUE THREAD

**Issue by AshleyPothecary** [manogi/nova-tiptap#34]
Not an issue but a proposal.

Is it possible to add `title` attributes to the buttons in the editor toolbar? So when you hover over each button a helpful hint shows. Much like the GitHub editor here:

![image](https://user-images.githubusercontent.com/15107279/109003141-f909a000-769e-11eb-85e0-f5d77fc659aa.png)

Mock up using Chrome dev-tools:
![image](https://user-images.githubusercontent.com/15107279/109009041-f2caf200-76a5-11eb-810e-fe896ca0e53a.png)

Whilst many of us developers will recognise the editor icons, there are some clients (the ultimate the end user) who may not.

**Comment by manogi** [comment]
This is a good idea. This would have to be translatable (I can provide German and English). And maybe the regular "title" attribute is not enough, maybe a tooltip like you said here in Github would be nice.

Would you like to PR this?

**Comment by manogi** [comment]
I just saw you seem to be new on GitHub - with "PR" I mean write a pull request, and if that is not possible for you, no problem, I will add this when I get around to it.

**Comment by AshleyPothecary** [comment]
@manogi I'm certainly new to contributing but I am happy to give this a shot. I'm sure I can spare some time this week or next to look into this 😄

**Comment by manogi** [comment]
This is done now (in English and German):

<img width="802" alt="CleanShot 2021-08-22 at 18 45 19@2x" src="https://user-images.githubusercontent.com/1419634/130363272-dbeab8b1-b05f-4811-a902-1f9fb06cd931.png">
