### ISSUE TITLE
How about a horizontal rule?

### ISSUE THREAD

**Issue by stuartcusackie** [manogi/nova-tiptap#35]
You have probably considered it already and maybe rejected the idea, but a horizontal rule button would be useful in my case.

No big deal! Thanks for the package!

**Comment by manogi** [comment]
Hey there - this feature has somehow been started, but not finished.

From v1.4.1 on this is now implemented and the Readme is updated. The button is called `'horizontal_rule'`.

**Comment by stuartcusackie** [comment]
Fantastic! Thanks again!
