### ISSUE TITLE
feat: text align

### ISSUE THREAD

**Issue by ibrunotome** [manogi/nova-tiptap#36]
Hi! I was hyped using the package until I noticed that there isn't an option to centralize text, is it possible to add it?

**Comment by manogi** [comment]
Hey there - at the moment I still use tiptap version 1 for this package, and there is no core or even third-party extension for text alignment. As I wouldn't use it myself, my motivation for writing an extension isn't really there. BUT: in version 2 of tiptap there will be such an extension and as soon as version 2 is out of beta, I will use it for my package and will include text alignment as well.

**Comment by manogi** [comment]
Hi there, I published the new version 2.0. Text alignment ist now possible:

<img width="812" alt="CleanShot 2021-08-22 at 18 43 48@2x" src="https://user-images.githubusercontent.com/1419634/130363222-55ed26d9-67aa-41f2-bbd6-009d66beba78.png">

You need to add the button "textAlign" (please the the readme for all the new buttons).

**Comment by ibrunotome** [comment]
The style looks great! Props for that!
