### ISSUE TITLE
Too much html in edit html

### ISSUE THREAD

**Issue by bcoelhodev** [manogi/nova-tiptap#37]
Hi,

In edit html this is happening:
<img width="1101" alt="Screenshot 2021-06-24 at 12 36 40" src="https://user-images.githubusercontent.com/13311052/123256923-6c0a1280-d4e9-11eb-9114-83fd73846227.png">

I'm using v1.4.1 and laravel nova v3.20.0.

**Comment by manogi** [comment]
Hi there, could you please elaborate? Where does this html come from?

**Comment by bcoelhodev** [comment]
Sorry, the error is in the seeder.

Thanks.
