### ISSUE TITLE
Request: New tab to link

### ISSUE THREAD

**Issue by bcoelhodev** [manogi/nova-tiptap#38]
Hi,

Is it possible to implement the option _new tab_ (`target="_blank"`) to link?

**Comment by manogi** [comment]
Hi there,

I published a new major version 2.0 now - there you can set "open in new window":

<img width="812" alt="CleanShot 2021-08-22 at 18 43 48@2x" src="https://user-images.githubusercontent.com/1419634/130363188-01d1a96f-9d81-4580-b716-2e3bddcd7591.png">

**Comment by Reached** [comment]
@manogi you are an absolute LEGEND!

Thank you for implementing this, and for continuing the work on nova-tiptap!
