### ISSUE TITLE
subscript and superscript

### ISSUE THREAD

**Issue by phpMagpie** [manogi/nova-tiptap#42]
I can see this was added in version 1.1.1(?) in response to the following issue:
https://github.com/manogi/nova-tiptap/issues/25

The buttons show when added to the field, but don't appear to be working.  

Have some updates from the following commit been lost in the latest version?
https://github.com/manogi/nova-tiptap/commit/10ceb8eacbf4845901fd0c1910e55b1f4b8a0edf#diff-b1e358490779f68e26ce0c95ff13cbff5b677aa150dd26bc5cf20b066b765b7c

**Comment by manogi** [comment]
Thank you for finding this issue @phpMagpie - it is now fixed in v2.1.3.

**Comment by phpMagpie** [comment]
I was just about to submit a PR ... you are fast 😄
