### ISSUE TITLE
It works great, but clients need  change the font color 

### ISSUE THREAD

**Issue by orchie** [manogi/nova-tiptap#45]
oh my god...
I saw this https://github.com/manogi/nova-tiptap/issues/3
but the  tiptap  https://github.com/ueberdosis/tiptap
alread has font color
https://github.com/ueberdosis/tiptap/issues/1362
can you add it?
thanks

**Comment by orchie** [comment]
@manogi thanks!
can you give me some document about how to  extend acustom button?
the color picker I think use ```<input type="color" >```  enough.
I will try to make it out.

**Comment by manogi** [comment]
@orchie sorry, but you will have to look at the code - I have no time to write docs how to contribute to this package. But please, before you start writing a PR: keep in mind that I might not accept the PR for one reason or another, so if you don't want to take the risk of spending time on this for nothing, you probably better should think twice.

A different solution would be to fork the repo and use your own solution for a while and come back to this place from time to time to see when I have implemented a font color picker. Then you could revert to this original repo in your app.
