### ISSUE TITLE
Wrong attributes in links

### ISSUE THREAD

**Issue by Aliaaaam** [manogi/nova-tiptap#49]
- `download=""` attribute wrongly applied to all links which is force the browser to download the page instead of navigating it.
- `title=""` applied to all links and can not modified by the editor which is not good for SEO.
- `rel="noopener noreferrer nofollow"` applied to internal links which is not good for SEO (would be best if we can choose the rel mode).

**Comment by manogi** [comment]
Hi @Aliaaaam , regarding the `download` attribute: there was a version a while back that introduced this problem. For a short while, the empty `download` attribute was accidentally added when saving. That is remedied since quite some time, but unfortunately you will have to save the text in Nova once to remove those `download` attributes (warning: Nova only really saves if some field is altered, so you might have to add a blank space somewhere or something similar).

**Comment by manogi** [comment]
I corrected the way the link attributes are added (Tiptap is a bit complicated in this regard). Now there are no empty attributes anymore, and the attributes are editable:

<img width="846" alt="CleanShot 2022-01-10 at 12 14 22@2x" src="https://user-images.githubusercontent.com/1419634/148757264-3515ebee-1949-4870-950e-3886bbda3971.png">

**Comment by Aliaaaam** [comment]
Thanks for your quick support, Is it added on 2.7.0? 
I have update it via composer but my nova still loads old IDE, is there any thing else should I do?

**Comment by manogi** [comment]
composer update with "manogi/nova-tiptap": "^2.7.0" should work. It did in my test.

**Comment by Aliaaaam** [comment]
![Screen Shot 1400-10-20 at 18 59 05](https://user-images.githubusercontent.com/88658555/148792185-256f1dc2-05d9-44c5-a669-9bd80bdf7e81.png)
Did exactly same thing but actions not working, seems nova load old vue bundle

**Comment by manogi** [comment]
can you please post your composer.json?

**Comment by Aliaaaam** [comment]
sure

```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "repositories": [
        {
            "type": "path",
            "url": "./nova"
        }
    ],
    "require": {
        "php": "^7.2.5",
        "alvinhu/nova-child-select": "^1.0",
        "anaseqal/nova-sidebar-icons": "^0.0.3",
        "davidpiesse/nova-toggle": "^0.0.6",
        "epartment/nova-dependency-container": "^1.2.8",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^1.0",
        "ghasedak/laravel": "^1.0",
        "guzzlehttp/guzzle": "^6.3",
        "hekmatinasser/verta": "1.11.8",
        "inspheric/nova-indicator-field": "^1.43",
        "inspheric/nova-url-field": "^1.4",
        "intervention/image": "^2.5",
        "laravel/framework": "^7.0",
        "laravel/nova": "*",
        "laravel/tinker": "^2.0",
        "manogi/nova-tiptap": "^2.7.0",
        "orlyapps/nova-belongsto-depend": "^2.0",
        "piwik/device-detector": "^3.10",
        "predis/predis": "^1.1",
        "shetabit/payment": "^4.0",
        "tymon/jwt-auth": "^1.0"
    },
    "require-dev": {
        "facade/ignition": "^2.0",
        "fzaninotto/faker": "^1.9.1",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^4.1",
        "phpunit/phpunit": "^8.5",
        "jenssegers/mongodb": "^3.7.0",
        "torann/hashids": "^2.0",
        "spatie/laravel-sitemap": "^5.8.0"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}
```

**Comment by manogi** [comment]
Looks OK. Also you might need to clear your browser cache - I always have the browser cache disabled when testing so that did not occur to me before.

**Comment by Aliaaaam** [comment]
I also test it in other browser and an other system, it seems the javascript bundle cached somewhere on Laravel side and I don't know how to clear it!

**Comment by manogi** [comment]
Is this local or on a remote server?

Did you try to run php artisan nova:publish or php artisan view:clear?

I'm not sure about this because I don't seem to need to run this, but maybe the view cache needs to be cleared.

Also I see two empty buttons - which ones are those supposed to be?

**Comment by Aliaaaam** [comment]
`php artisan view:clear` fixed the issue.
Awesome update, thank you!
