### ISSUE TITLE
Request: Add Table Support

### ISSUE THREAD

**Issue by bcorcoran** [manogi/nova-tiptap#5]
Could you add table support (https://tiptap.scrumpy.io/tables) at some point?

**Comment by milewski** [comment]
Was was trying to add this just now and submit a PR, however the dependency on that pro font-awesome icons is overkill.... I would suggest getting ride of it and using some free ones. however I still would like this feature.. seems pretty straight forward to implement... any chance of an update @manogi ?

**Comment by manogi** [comment]
@milewski You are right - tbh this is my first real open source contribution and I did not think about other contributors having to add font awesome pro. I will remove that dependency in my next update. Trying to do that today, don't know if I can finish it.

**Comment by manogi** [comment]
I have removed the dependency now in the new release 0.3.2.

**Comment by manogi** [comment]
It is true that the table support seems straightforward - I will give it a shot myself, and if I don't succeed I will get back to you, @milewski

**Comment by manogi** [comment]
Am pretty far with adding table support.
Had to fix a bug introduced in the 0.3.2 release though - it is fixed in 0.3.3.

Now I just need some icons to use for all those table buttons ("add row below", "add row above" etc.).

**Comment by adrienne** [comment]
@manogi - Wordpress' Gutenberg uses Material Icons, which has a TON of options and you should be able to find some good ones. https://material.io/tools/icons/?style=baseline  

There's an icon font and SVGs available, whichever works better with the project.

**Comment by adrienne** [comment]
@manogi - any word on this? I'd really like to switch to this editor but currently table support is buggy (it won't let me add the `"resizeable = true"` part, and trying to edit tables is just very jumpy and i don't get all the row and column buttons properly.

**Comment by latwelve** [comment]
Hey @manogi has this project been abandoned? thank you

**Comment by manogi** [comment]
Not really abandoned, but I don't find any time next to customer work atm. This is an open source projects - PRs are welcome. I hope I find the time to get back to this project in the nearer future.

**Comment by manogi** [comment]
finally found the time to include table support (in v1.1.0):

![image](https://user-images.githubusercontent.com/1419634/93019323-8e741480-f5d6-11ea-8b0f-a02f4031da3f.png)


![image](https://user-images.githubusercontent.com/1419634/93019291-6b496500-f5d6-11ea-9507-c46c56caf389.png)

![image](https://user-images.githubusercontent.com/1419634/93019373-d2ffb000-f5d6-11ea-9101-383d2f86e73e.png)
