### ISSUE TITLE
No Detail Field anymore in 2.0

### ISSUE THREAD

**Issue by mstaack** [manogi/nova-tiptap#50]
Is there any reason to have an empty detail field in 2.0?

With 1.0 all worked fine on my side :)

https://github.com/manogi/nova-tiptap/blob/v2.7.0/resources/js/components/DetailField.vue

isn't adding v1 vue component enough?

**Comment by jolora** [comment]
Yes to me this seems like it must be a bug... I was surprised to find my TipTap fields missing on the detail view.

**Comment by manogi** [comment]
Hi there - the detail field now behaves the same as the Trix detail field: it shows a "Show content" button to expand the content. Also like the Trix fied using the `->alwaysShow()` method in the resource makes the content always visible in the detail view.

**Comment by manogi** [comment]
P.S. added in v2.7.1

**Comment by jolora** [comment]
Brilliant, thanks @manogi . I was on v2.7.0 ... v2.7.1 works a treat!

**Comment by mstaack** [comment]
brilliant stuff, thank you!
