### ISSUE TITLE
Doesn't work in Safari when used in an Action.

### ISSUE THREAD

**Issue by latwelve** [manogi/nova-tiptap#51]
Hey - if the tiptap field is used within an Action model then it is not selectable with a mouse or by tabbing into it. 

It works fine when used on an update or creation page.

Latest nova & package version

**Comment by manogi** [comment]
Hi there - I just added a Tiptap field to an action and had no problem selecting the field and writing into it. Please let me know a bit more about your setup, maybe paste the resource class, and maybe let me know your browser and version, thanks.

**Comment by latwelve** [comment]
Hey I think its on me doing something silly - I'll close this for now. Sorry for the false alert!
