### ISSUE TITLE
Issue rendering paragraph toolbar button (missing icon)

### ISSUE THREAD

**Issue by mikkellindblom** [manogi/nova-tiptap#52]
Seems like the icon for the paragraph button is missing in NormalButton.vue.

<img width="679" alt="Screenshot 2022-02-04 at 13 14 15" src="https://user-images.githubusercontent.com/5261690/152527326-4d248f4f-5332-4db0-8634-b2dc22c776f6.png">

**Comment by manogi** [comment]
Hi there, could you please paste your Resource Class, or just the Tiptap fields inside that class? I'm not sure which button you mean. There is no "paragraph" button. Just pressing enter inside Tiptap adds a new paragraph, no button is needed. All other block elements can be turned back into a paragraph by by toggling the button again (like H1, H2, Unordered List etc.).

**Comment by mikkellindblom** [comment]
Hi @manogi ,

I often use the "paragraph" button to reset text pasted from elsewhere, maybe that is just me? 

```            
Tiptap::make('Content', 'content')
                ->buttons([
                    'heading',
                    'paragraph',
                    '|',
                    'italic',
                    'bold',
                    '|',
                    'link',
                    'strike',
                    'underline',
                    'highlight',
                    '|',
                    'bulletList',
                    'orderedList',
                    '|',
                    'table',
                ])
                ->headingLevels([1, 2, 3, 4])
                ->onlyOnForms(),
```

Maybe the following would work:

File: [NormalButton.vue](https://github.com/manogi/nova-tiptap/blob/master/resources/js/components/buttons/NormalButton.vue):

```
Line 58:

else if (this.button == 'paragraph') {
    return ['fas', 'paragraph'];
}

Line 109:

else if (this.button == 'paragraph') {
    command.setParagraph();
}

```

**Comment by manogi** [comment]
Hmm. I'm not sure I would like the Paragraph button to be a "first class citizen", because people might think they actually need to use it. But I might consider adding the button, but not adding it to the Readme. I will think about it.

**Comment by mikkellindblom** [comment]
Sure thing, let me know what you decide :) Thanks!

**Comment by manogi** [comment]
I decided to add the button (is added in version v2.7.2), but I don't mention it in the Readme. Using feels a little strange to me, as there is no way to "untoggle" a paragraph, as the paragraph is the default block node. I hope it fits your use case!

**Comment by mikkellindblom** [comment]
Thank you @manogi!
