### ISSUE TITLE
Allow customisation of image inline setting 

### ISSUE THREAD

**Issue by kenneth-hendricks** [manogi/nova-tiptap#54]
Hi,

It would be great if this library allowed users to set the inline setting for the images extension. This is required if you want to allow images to be made linkable. From what i can see there is no way to set this currently.

https://tiptap.dev/api/nodes/image

**Comment by curder** [comment]
Need this.

**Comment by shaffe-fr** [comment]
Hey @manogi,
I'm preparing a PR for this issue, but I encounters troubles to install local dependencies because of FontAwesomePro.
Can I PR the updated sources? You'll only have to compile them.
Thanks

**Comment by manogi** [comment]
Yes, we can try this

**Comment by shaffe-fr** [comment]
IMO images should always be embed as inline. Do you agree or would you prefer a new imageSettings.inline option?
Thanks

**Comment by manogi** [comment]
It will take me a bit longer to answer this - I am currently not actively using Nova (or TipTap) and will have to re-install my testing environment for it.

**Comment by alexgilbertDG** [comment]
Any updates on this ?
I will open a PR if needed

**Comment by shaffe-fr** [comment]
Hey, I changed the rich text editor I'm using for creditor 4. I'll share what I already have.

**Comment by shaffe-fr** [comment]
Hey @alexgilbertDG, I have this https://github.com/shaffe-fr/nova-tiptap/tree/inline-image

**Comment by alexgilbertDG** [comment]
@manogi  Any update about this issue....
