### ISSUE TITLE
Update to Support Nova 4

### ISSUE THREAD

**Issue by cwray-tech** [manogi/nova-tiptap#55]
Now that Nova 4 is out, it would be great if we could update this field to support it. Let me know if you would like some help on this and I may be able to dedicate some time on it. For this field I don't believe we will have too many changes to make.

**Comment by manogi** [comment]
Hey there - yeah, I just read this today. You know what - I do would like some help with that. If you have the time, I look forward to your PR - but no pressure, of course. Thanks for offering your help!

**Comment by manogi** [comment]
I might also look into this. Will report back here, not very much time at them moment,

**Comment by gepopp** [comment]
Hey there,
if u really can do that update, sent me a link to buy u a coffee ;)

**Comment by cwray-tech** [comment]
I'm on a tight deadline with a work project as soon as I'm in a better place with that, I can give it a go, but if someone has more time now feel free to go ahead!

**Comment by manogi** [comment]
I will look into it over the weekend.

**Comment by manogi** [comment]
I can tell you - upgrading packages for Nova 4 is no fun when you're actually using Vue in the package... but it is now done. What seems to be gone in Nova 4 is the option to make the field wider (without the white space to the right of the field) - even the Trix field is narrower now, and for now I cannot make the Tiptap field span the entire available space, unfortunately.

Version 3 of Tiptap is now available for Nova 4.

**Comment by cwray-tech** [comment]
@manogi I super appreciate you putting in that work. Thank you so much!

Hopefully this next week I'll be able to test it in a client project.

The Nova team really did change a lot of things with this new upgrade. hopefully it was a good decision on their part..

**Comment by gepopp** [comment]
@manogi magnific, works like a charm!!

**Comment by manogi** [comment]
@gepopp thanks for noticing this - it is now fixed.

**Comment by gepopp** [comment]
@manogi you are awesome!!

**Comment by manogi** [comment]
@gepopp lol not really but thanks!
