### ISSUE TITLE
Link modal is wrongly placed on tiptap v2.8.0 on Nova 3

### ISSUE THREAD

**Issue by cfc7-unikent** [manogi/nova-tiptap#56]
**Versions:**
* Nova: 3.32.0
* TipTap: 2.8.8

### Description
When pressing the link button the link modal is placed down in the bottom right just off the screen.  

![2 8 0 - modal placement and toolbars](https://user-images.githubusercontent.com/31033292/165120113-d4bed54b-1975-4ce2-a3f4-e74f2c868cb8.gif)

In the previous version 2.7.6 the modal is placed in the middle as expected.

![2 7 6 - toolbars](https://user-images.githubusercontent.com/31033292/165120135-25b5adbe-ca1e-45ba-9436-e1901c9662c6.gif)

Note in both versions then having more than TipTap field seems to result in the toolbars of each field on the screen appearing when the link modal is viewed.

**Comment by manogi** [comment]
HI there, thank you for notifying me. This is now fixed in v2.8.1

**Comment by manogi** [comment]
Ah well - the thing with the toolbars is not yet fixed.

**Comment by cfc7-unikent** [comment]
Many thanks for the fix - that does resolve the issue with the placement. :-)

What would be best about the thing with the toolbars? Would you like me to keep this issue open or would you like me to add it as a new separate issue?

**Comment by manogi** [comment]
Please keep it open - I'm fixing it with vue-portal

**Comment by manogi** [comment]
The toolbar situation is now fixed in v2.8.2

**Comment by cfc7-unikent** [comment]
That is absolutely brilliant! Many, many thanks @manogi :-)

All looks perfect to me 🎉
