### ISSUE TITLE
Multiple Headimgs?

### ISSUE THREAD

**Issue by gepopp** [manogi/nova-tiptap#57]
Hi there, 
Im not aure if its a Bug or this is on purpose but its not possible tlo set multiple headings of the same kind in one fiel.

So after setting for eg. the first h3 the and mark another line line the h3 Button is not working anymore?

**Comment by manogi** [comment]
Hi there, no, that is not in purpose - I am investigating.

**Comment by manogi** [comment]
@gepopp  phew some more Vue 3 madness but this is now fixed.

**Comment by manogi** [comment]
@gepopp in v3.0.6
