### ISSUE TITLE
Text content shows through link modal 

### ISSUE THREAD

**Issue by joostvanhoof** [manogi/nova-tiptap#60]
On version 3.0.6:

<img width="827" alt="Screenshot 2022-06-27 at 07 41 27" src="https://user-images.githubusercontent.com/5268113/175867687-483f0969-2492-4311-81e9-2e16f0f66019.png">

**Comment by manogi** [comment]
@joostvanhoof hi there - this is now fixed in v3.0.7

**Comment by joostvanhoof** [comment]
Awesome, thanks! I did notice that there is a similar issue with the menu bar. If you have enough content then the menu bar becomes sticky (as expected and this works). When it does, you can not click any of the buttons on the menu bar anymore.

<img width="621" alt="Screenshot 2022-06-30 at 22 35 14" src="https://user-images.githubusercontent.com/5268113/176773887-274a0275-8ffe-4686-9f54-c8665fb58be6.png">

**Comment by manogi** [comment]
@joostvanhoof this is now repaired in v3.1.2. Laravel Nova frustratingly keeps removing tailwind classes which then have no effect anymore in third party addons like mine.
