### ISSUE TITLE
Support for dependsOn

### ISSUE THREAD

**Issue by chriswd** [manogi/nova-tiptap#61]
Your editor is really cool! It would be very nice to have support [for the Nova 4 dependsOn() - Feature](https://nova.laravel.com/docs/4.0/resources/fields.html#dependent-fields), for example to set a different default content in depending on a Select box.

Thanks a lot!

**Comment by manogi** [comment]
@chriswd I'm not using Nova 4 that much yet (some third party packages do not support it yet).
Would you like to PR this functionality, maybe?

**Comment by chriswd** [comment]
Hi Sebastian, sorry, but I'm not an expert for your component, more a Nova beginner. So I can't build it myself.
