### ISSUE TITLE
Content is saved to null without touching it

### ISSUE THREAD

**Issue by axeldotdev** [manogi/nova-tiptap#63]
Hello! 👋

I have an issue with the editor integration on a client site that I can't figure out.

When I go to the edit form of a page (one of my resources), I update the title for example then I save, and then one or more contents in one of the layouts will be saved at `null`.

I'm not sure if the issue comes from this package or from my code, anyone have an idea?
Maybe mixing with layouts classes from Flexible Content is an issue?
Maybe having multiple editors on the same form is a problem?

I use PHP 8.1, Laravel 9, Laravel Nova 4 and the Flexible Content package.

Can you tell me how to test it? Clone the repo and require it into my nova-components maybe ? That way I could use logs and Vue devtool ?

Below my layout class with the editor in it:

![Screenshot 2022-09-23 at 11 42 55](https://user-images.githubusercontent.com/10605697/191934201-7c611e2b-a5fb-4149-99bd-a0d04cbd2175.png)

If this issue needs to be in the discussions let me know and I will move it. 👍

**Comment by manogi** [comment]
Hi there, I have not tried to integrate TipTap in the Flexible Content package in Nova 4 yet, maybe there is some strange Javascript problem. Unfortunately I don't have much time for checking it, maybe you can fork it and see if you find the error.

**Comment by axeldotdev** [comment]
Hello, thanks for you quick response, I will try to investigate. 👍
