### ISSUE TITLE
JS error on console

### ISSUE THREAD

**Issue by vincent-athenaads** [manogi/nova-tiptap#67]
console:
![截圖 2023-02-13 下午4 22 25](https://user-images.githubusercontent.com/125233708/218406599-5e09658e-da22-49a6-941a-45d7949d4535.png)
![截圖 2023-02-13 下午4 22 47](https://user-images.githubusercontent.com/125233708/218406610-6cd520e7-ad6b-4f29-b5dc-a390aba0ed55.png)

php:
<img width="566" alt="截圖 2023-02-13 下午4 23 17" src="https://user-images.githubusercontent.com/125233708/218406696-3539d717-17cb-49b0-a278-f47fc10ce0e6.png">

version:
php 7.4.21
nova 4.21.0
tiptap 3.0.3

**Comment by manogi** [comment]
Nova TipTap only works with PHP 8.0 or higher. As stated in the composer.json, so you shouldn't actually have been able to install it via composer on PHP 7.4?
