### ISSUE TITLE
Issue with "?" symbol in editor

### ISSUE THREAD

**Issue by ArmeniaH** [manogi/nova-tiptap#7]
Whenever I am trying to write "?" symbol, the global search gets the focus, so it seems there is conflict between laravel nova global search shortcut key.

Any idea how to fix this ?

**Comment by manogi** [comment]
Hey @ArmeniaH - thank you for noticing this. It is now fixed in 0.3.4.

Also thank you to @bcorcoran for showing the fix in https://github.com/laravel/nova-issues/issues/117#issuecomment-493263994
