### ISSUE TITLE
Can't create a link.

### ISSUE THREAD

**Issue by lewis-sixth** [manogi/nova-tiptap#8]
When I select the link button the tooltip appears, but I cant select the input to type in a url. When I click the input it highlights like a button click. The close button works fine,

When I the link button.
<img width="237" alt="Capture" src="https://user-images.githubusercontent.com/43447977/66044542-ad8aab00-e519-11e9-8479-3a40d44bda12.PNG">

When I click and hold the link form.
<img width="238" alt="Capture2" src="https://user-images.githubusercontent.com/43447977/66044563-b24f5f00-e519-11e9-971f-bc17b4d9f895.PNG">

**Comment by stuartcusackie** [comment]
Exact same problem here. Just installed the package today.
